name: GameOver
version: 0.7.0
main: org.trentech.gameover.Main
api-version: 1.13
authors: [TrenTech]
description: You Lose!
website: trentech.org
softdepend: [Essentials, LogBlock, Vault]
load: POSTWORLD
commands:
  gameover:
    usage: </command>
    aliases: [go]
Permissions:
  GameOver.use:
    default: false
  GameOver.reload:
    default: true
  GameOver.reset:
    default: true